DROP TABLE IF EXISTS todos;

CREATE TABLE todos (
    id SERIAL PRIMARY KEY,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    done BOOLEAN DEFAULT FALSE,
    title VARCHAR(255) NOT NULL
);

-- CLI TO RUN THIS FROM THE ROOT DIR -- ADJUST PATH IF NECESSARY
-- NEEDED TO NAVIGATE INTO THE DB TO DO THIS...
-- \i internal/store/db/tables.sql